#!/usr/bin/env python3
"""Anchor brownfield marker writer — ``Anchor.md`` + machine sidecar (stdlib).

When Anchor adopts a folder's pre-existing trio artifacts it leaves a small,
human-readable ``Anchor.md`` at the folder ROOT describing the folder's R&D
STRUCTURE — counts, relative paths, titles, last-scanned — and a machine sidecar
``.anchor/projects/<id>/discovery.json`` holding the full :class:`ScanResult`.

Hard rules (honesty + safety contract):
  - ``Anchor.md`` is STRUCTURE ONLY: counts, relative paths, titles. It NEVER
    embeds file contents or secrets. (Titles come from the scanner, which only
    reads a markdown heading — never bulk content.)
  - Written under ``paths.WRITE_LOCK`` (concurrency-safe; one consistent file
    under N concurrent opens).
  - Hash-compare NO-CHURN: the body is compared (modulo the volatile
    "last scanned" timestamp) and the file is rewritten ONLY when the structure
    changed — opening an unchanged folder twice does NOT rewrite ``Anchor.md``.
  - Sectioned for N-projects-per-folder: each registered project sharing the
    folder gets its own section.
  - Commit-safe: no absolute paths, no secrets, no personal data.

Stdlib only.
"""

import hashlib
import json
import re
import time
from pathlib import Path

import paths as _paths
import rnd_registry as _rnd
import brownfield_scan as _bscan
import effort_history as _eh

ANCHOR_MD_NAME = "Anchor.md"
SIDECAR_NAME = "discovery.json"

# Marker delimiting the no-churn-comparable body (everything but the timestamp).
_GENERATED_RE = re.compile(r"^_Last scanned:.*$", re.M)


def sidecar_path(folder_path, project_id: str) -> Path:
    """``<folder>/.anchor/projects/<id>/discovery.json`` (not created)."""
    return _rnd.project_store_dir(folder_path, project_id) / SIDECAR_NAME


def anchor_md_path(folder_path) -> Path:
    """``<folder>/Anchor.md`` (not created)."""
    return Path(folder_path) / ANCHOR_MD_NAME


def _projects_for_folder(folder_path) -> list:
    """Registered projects whose folder_path matches ``folder_path`` (ordered)."""
    target = str(Path(folder_path))
    out = []
    for e in _rnd.list_projects():
        try:
            if str(Path(e.get("folder_path", ""))) == target:
                out.append(e)
        except (TypeError, ValueError):
            continue
    out.sort(key=lambda e: (e.get("priority", 2), e.get("name", "").lower()))
    return out


def _render_project_section(entry: dict, scan) -> str:
    """Render one project's section: per-lane counts + relative artifact paths.

    STRUCTURE ONLY — counts, relative paths, titles. No file contents.
    """
    name = entry.get("name", "") or "(unnamed)"
    pid = entry.get("id", "")
    lines = [f"## {name}", "", f"- id: `{pid}`", ""]
    # Real vs imported per lane (from the live effort store).
    folder = entry.get("folder_path", "")
    lines.append("### Lanes (real runs + imported)")
    lines.append("")
    for lane in _eh.ROLLUP_LANES:
        try:
            lr = _eh.lane_rollup(folder, pid, lane)
        except Exception:
            lr = {"effort_count": 0, "discovered_count": 0}
        lines.append(
            f"- **{lane}** — {lr.get('effort_count', 0)} run"
            f"{'s' if lr.get('effort_count', 0) != 1 else ''}, "
            f"{lr.get('discovered_count', 0)} imported")
    lines.append("")
    # Discovered artifacts (relative paths + titles only).
    lines.append("### Discovered artifacts (structure only)")
    lines.append("")
    any_art = False
    for lane in _bscan.LANES:
        arts = scan.by_lane.get(lane, [])
        if not arts:
            continue
        any_art = True
        lines.append(f"- {lane}:")
        for a in arts:
            title = a.get("title", "") or a.get("rel", "")
            lines.append(f"  - `{a.get('rel', '')}` — {title}")
    if scan.docs:
        any_art = True
        lines.append("- docs (listed, not adopted):")
        for a in scan.docs:
            lines.append(f"  - `{a.get('rel', '')}`")
    if not any_art:
        lines.append("- (none discovered)")
    lines.append("")
    return "\n".join(lines)


def _render_anchor_md(folder_path, projects, scan) -> str:
    """Render the full Anchor.md body (structure only, sectioned)."""
    head = [
        "# Anchor.md",
        "",
        "> Auto-generated by Anchor's R&D control surface. **Structure only** —"
        " counts, relative paths, and titles of discovered trio artifacts. This"
        " file never contains file contents or secrets. Safe to commit.",
        "",
        f"_Last scanned: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())}_",
        "",
    ]
    body = []
    if not projects:
        body.append("_No registered R&D projects for this folder._\n")
    for entry in projects:
        body.append(_render_project_section(entry, scan))
    return "\n".join(head) + "\n" + "\n".join(body)


def _comparable(text: str) -> str:
    """Strip the volatile timestamp line so unchanged structure hashes equal."""
    return _GENERATED_RE.sub("_Last scanned: <ts>_", text or "")


def _body_hash(text: str) -> str:
    return hashlib.sha1(_comparable(text).encode("utf-8")).hexdigest()


def write_anchor_md(folder_path) -> dict:
    """Render + write ``Anchor.md`` (no-churn) and the per-project sidecar(s).

    Returns ``{"written": bool, "reason": str, "path": str, "sidecars": [...]}``.
    Best-effort: a missing/unwritable folder yields ``written=False`` with a
    reason and never raises.
    """
    try:
        folder = Path(folder_path)
        if not folder.is_dir():
            return {"written": False, "reason": "folder-missing",
                    "path": "", "sidecars": []}
    except OSError:
        return {"written": False, "reason": "folder-error",
                "path": "", "sidecars": []}

    with _paths.WRITE_LOCK:
        projects = _projects_for_folder(folder)
        scan = _bscan.scan(str(folder))
        new_text = _render_anchor_md(folder, projects, scan)
        md_path = anchor_md_path(folder)

        # No-churn: compare the structure-only hash; rewrite only if changed.
        written = False
        reason = "unchanged"
        try:
            old_text = md_path.read_text(encoding="utf-8") if md_path.exists() else ""
        except OSError:
            old_text = ""
        if _body_hash(old_text) != _body_hash(new_text):
            try:
                md_path.write_text(new_text, encoding="utf-8")
                written = True
                reason = "written"
            except OSError as e:
                return {"written": False, "reason": f"write-failed: {e}",
                        "path": str(md_path), "sidecars": []}

        # Machine sidecar(s): full ScanResult per registered project.
        sidecars = []
        for entry in projects:
            pid = entry.get("id", "")
            if not pid:
                continue
            sc = sidecar_path(folder, pid)
            try:
                sc.parent.mkdir(parents=True, exist_ok=True)
                scan_dict = scan.to_dict()
                # Preserve non-scan keys (e.g. `handoffs`) that other modules
                # append to the sidecar — scan.to_dict() owns only the scan
                # keys, so a naive overwrite would DROP them on every rescan.
                old = sc.read_text(encoding="utf-8") if sc.exists() else ""
                merged = dict(scan_dict)
                try:
                    prev = json.loads(old) if old else {}
                except (json.JSONDecodeError, ValueError):
                    prev = {}
                if isinstance(prev, dict):
                    for k, v in prev.items():
                        if k not in scan_dict:
                            merged[k] = v
                payload = json.dumps(merged, indent=2, ensure_ascii=False)
                # No-churn for the sidecar too (compare scan-owned content only).
                if _sidecar_changed(old, payload):
                    sc.write_text(payload, encoding="utf-8")
                sidecars.append(str(sc))
            except OSError:
                continue

        return {"written": written, "reason": reason, "path": str(md_path),
                "sidecars": sidecars}


#: Keys the brownfield scan OWNS in the sidecar. The no-churn comparison is
#: restricted to these (minus the volatile ``generated_at``) so preserved
#: non-scan keys like ``handoffs`` neither trigger a spurious rewrite nor get
#: dropped.
_SCAN_KEYS = frozenset(("by_lane", "docs", "counts", "generated_at",
                        "root", "truncated"))


def _sidecar_changed(old_json: str, new_json: str) -> bool:
    """True if the SCAN-OWNED sidecar content changed.

    Compares only the scan-owned keys (ignoring ``generated_at`` and any
    preserved non-scan keys such as ``handoffs``), so a no-op rescan with a
    ``handoffs`` key present reports no change AND a real scan change still
    rewrites.
    """
    def _strip(s):
        try:
            d = json.loads(s)
        except (json.JSONDecodeError, ValueError):
            return None
        if not isinstance(d, dict):
            return None
        scan_only = {k: v for k, v in d.items()
                     if k in _SCAN_KEYS and k != "generated_at"}
        return json.dumps(scan_only, sort_keys=True)
    return _strip(old_json) != _strip(new_json)
